stages:
  - build

build:
  stage: build
  image: python:3
  script:
    - python -m venv venv
    - source venv/bin/activate
    - echo "Estou aqui de propósito"
    - pip install -r requirements.txt
    - python app.py
