stages:
  - test
  

build:
  stage: build
  image: python:3
  script:
    - python -m venv venv
    - source venv/bin/activate
    - echo "Estou aqui de propósito"
    - python app.py
    
